apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  labels:
    app: login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-app
        image: suhasdhoke92/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080
